baseurl = "http://kgolding.com/"
languageCode = "en-us"
title = "Kevin Golding"
theme = "hyde-x"
preserveTaxonomyNames = true

[[menu.main]]
    name = "Projects"
    url = "/project/"

[taxonomies]
    category = "categories"

[blackfriday]
    hrefTargetBlank = true

[author]
    name = "Kevin Golding"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[params]
    photo = "/img/KevinCaricature2Oval150x180.png"
    linkedin = "https://www.linkedin.com/in/kevingolding"
    twitter = "https://twitter.com/kgoldinguk"
    googleplus = "https://plus.google.com/+KevinGolding"
    stackOverflow = "http://stackexchange.com/users/3388933/kgolding"
    facebook = "https://www.facebook.com/kevin.golding.uk"

    hideReadingTime = true
    theme = "theme-base-0d"
    customCSS = "/css/kgolding.css"
    home = "Home"


