baseURL = "https://kgolding.co.uk/"
languageCode = "en-gb"
title = "Kevin Golding"
theme = "beautifulhugo"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
# pygmentsStyle = "trac"
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-83317619-1"

enableGitInfo = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 500

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 800

[[menu.main]]
    name = "Applications"
    url = "/application/"
    weight = 920

[[menu.main]]
    name = "Companies"
    url = "/company/"
    weight = 900

[taxonomies]
    category = "categories"

[blackfriday]
    hrefTargetBlank = true

[author]
    name = "Kevin Golding"
    email = "kevin@kgolding.co.uk"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"


[Params]
  homeTitle = "Kevin Golding"
  subtitle = "Software/hardware engineer aka technologist"
  mainSections = ["post","posts","application", "company", "project"]
  logo = "img/KevinCaricature2Oval150x180.png" # Expecting square dimensions
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  commit = "https://github.com/kgolding/website-kgolding.co.uk/tree/"
  rss = true
  comments = true
  readingTime = false
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Kevin Golding"
  website = "kgolding.co.uk"
  email = "kevin@kgolding.co.uk"
  facebook = "kevin.golding.uk"
  github = "kgolding"
  gitlab = "kevin"
#  bitbucket = "username"
  twitter = "kgoldinguk"
#  reddit = "username"
  linkedin = "kevingolding"
#  xing = "username"
  stackoverflow = "users/2844276/kgolding"
#   snapchat = "username"
#   instagram = "username"
  youtube = "user/kgolding" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"
#   codepen = "username"
#   mastodon = "url"
#   kaggle = "username"
#   weibo = "username"
#   slack = "kgolding"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4